In [ ]:
import pandas as pd
import numpy as np

# Задание 1
Определите, какому фильму было выставлено больше всего оценок 5.0.

In [ ]:
movies = pd.read_csv('/content/movies.csv')
ratings = pd.read_csv('/content/ratings.csv')

In [ ]:
movies.head(20)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller

In [ ]:
ratings.head(20)

    userId  movieId  rating  timestamp
0        1        1     4.0  964982703
1        1        3     4.0  964981247
2        1        6     4.0  964982224
3        1       47     5.0  964983815
4        1       50     5.0  964982931
5        1       70     3.0  964982400
6        1      101     5.0  964980868
7        1      110     4.0  964982176
8        1      151     5.0  964984041
9        1      157     5.0  964984100
10       1      163     5.0  964983650
11       1      216     5.0  964981208
12       1      223     3.0  964980985
13       1      231     5.0  964981179
14       1      235     4.0  964980908
15       1      260     5.0  964981680
16       1      296     3.0  964982967
17       1      316     3.0  964982310
18       1      333     5.0  964981179
19       1      349     4.0  964982563

In [ ]:
movie_rating = movies[['movieId', 'title']].merge(ratings[['movieId', 'rating']], how='inner', on='movieId')

In [ ]:
# только оценки 5
five_star = movie_rating.loc[movie_rating['rating'] == 5]

# группируем, считаем пятерки, сортируем и выводим первый фильм
five_star.groupby(by=['movieId', 'title']).count().sort_values(by='rating', ascending=False).head(1)

                                          rating
movieId title
318     Shawshank Redemption, The (1994)     153

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. Не учитывайте в расчётах отрицательные значения quantity.

In [ ]:
power = pd.read_csv('/content/power.csv')

In [ ]:
# отфильрованный датафрейм
filtred_power = power[(power['quantity'] >= 0) &
                      (power['category'].isin([4, 12, 21])) &
                      (2005 <= power['year']) & (power['year'] <= 2010) &
                      (power['country'].isin(['Estonia', 'Latvia', 'Lithuania']))]
filtred_power['quantity'].sum() #суммарное потребление

240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas DataFrame. Вы можете взять любые страницы.

сайт: https://statpsy.ru/t-student/t-test-tablica/

In [ ]:
url = 'http://www.pogodaiklimat.ru/weather.php?id=27402&bday=1&fday=30&amonth=4&ayear=2024&bot=2'
student_table = pd.read_html(url, encoding='UTF-8')[1]

#Меняем название столбцов на значение первой колонки
# cols = student_table.iloc[0]
# student_table.columns = cols
# student_table = student_table.iloc[1:]

In [ ]:
student_table

[                      0                   1
 0    Время (UTC),\tдата  Время (UTC),\tдата
 1                    00                1.04
 2                    03                1.04
 3                    06                1.04
 4                    09                1.04
 ..                  ...                 ...
 236                  09               30.04
 237                  12               30.04
 238                  15               30.04
 239                  18               30.04
 240                  21               30.04

 [241 rows x 2 columns],
                     0                  1       2        3   \
 0    Ветер (напр.,м/с)  Ветер (напр.,м/с)  Видим.  Явления
 1                   ЮВ                  1   10 км      NaN
 2                   ЮВ                  2   10 км      NaN
 3                   ЮВ                  3   10 км      NaN
 4                    Ю                  2   10 км      NaN
 ..                 ...                ...     ...      ...
 236                 ЮЗ                  3   10 км      NaN
 237                  З             3 {10}   10 км      NaN
 238                 СЗ                  1   10 км      NaN
 239                 СЗ                  1   10 км      NaN
 240                 СЗ                  1   10 км      NaN

                                       4      5       6      7       8   \
 0                             Облачность  Т (С)  Тd (С)  f (%)  Тe (С)
 1                         6/0 [Ac trans]   +7.4    +4.4     81      +7
 2                         9/0 [Ac trans]   +8.6    +6.0     84      +7
 3               9/3 1000 м [Sc Ac trans]  +12.4    +7.8     74     +11
 4                  6/0 [Ac trans Ci fib]  +18.9    +8.0     49     +20
 ..                                   ...    ...     ...    ...     ...
 236  8/3 1000 м [Cu hum Ac trans Ci fib]  +21.7    +4.2     32     +22
 237                10/10 1000 м [Cb cap]  +22.0    +4.1     31     +22
 238      9/3 1000 м [Sc Ac trans Ci fib]  +19.5    +9.1     51     +22
 239                8/0 [Ac trans Ci fib]  +16.3    +9.0     62     +17
 240                8/0 [Ac trans Ci fib]  +14.3    +7.5     64     +15

           9             10       11        12        13        14      15  \
 0    Тes (С)  Комфортность  P (гПа)  Po (гПа)  Тmin (С)  Tmax (С)  R (мм)
 1         +7         тепло   1010.6     992.9       NaN       NaN     NaN
 2         +7         тепло   1008.6     991.1      +7.3       NaN     NaN
 3        +12         тепло   1007.0     989.8      +7.3       NaN     NaN
 4        +27         тепло   1005.1     988.3       NaN       NaN     NaN
 ..       ...           ...      ...       ...       ...       ...     ...
 236      +27       комфорт   1027.7    1010.6       NaN       NaN     NaN
 237      +22       комфорт   1026.1    1009.0       NaN       NaN     NaN
 238      +23       комфорт   1025.4    1008.3       NaN       NaN     NaN
 239      +17         тепло   1025.3    1007.9       NaN     +23.1     NaN
 240      +15         тепло   1025.4    1007.9       NaN       NaN     NaN

            16      17
 0    R24 (мм)  S (см)
 1         NaN     NaN
 2         NaN     NaN
 3         NaN     NaN
 4         NaN     NaN
 ..        ...     ...
 236       NaN     NaN
 237       NaN     NaN
 238       NaN     NaN
 239       NaN     NaN
 240       NaN     NaN

 [241 rows x 18 columns]]